// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZYZfYII7nAbRl2ssCiEuB0YcufGnuUbo',
    appId: '1:185980805978:web:42ba06ef37031e13ee0963',
    messagingSenderId: '185980805978',
    projectId: 'rtrx-cc137',
    authDomain: 'rtrx-cc137.firebaseapp.com',
    storageBucket: 'rtrx-cc137.firebasestorage.app',
    measurementId: 'G-B3V5ZDZ3EC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0LMJwmNpVp2q5N5dVxzRIuxcZVfaNtnQ',
    appId: '1:185980805978:android:faec9db19ca6de22ee0963',
    messagingSenderId: '185980805978',
    projectId: 'rtrx-cc137',
    storageBucket: 'rtrx-cc137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmRzShvCWYBxiqCrgRB1JAPNaQGNYi0TY',
    appId: '1:185980805978:ios:e549175fde4668d6ee0963',
    messagingSenderId: '185980805978',
    projectId: 'rtrx-cc137',
    storageBucket: 'rtrx-cc137.firebasestorage.app',
    iosBundleId: 'com.rtrx.project1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmRzShvCWYBxiqCrgRB1JAPNaQGNYi0TY',
    appId: '1:185980805978:ios:e549175fde4668d6ee0963',
    messagingSenderId: '185980805978',
    projectId: 'rtrx-cc137',
    storageBucket: 'rtrx-cc137.firebasestorage.app',
    iosBundleId: 'com.rtrx.project1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZYZfYII7nAbRl2ssCiEuB0YcufGnuUbo',
    appId: '1:185980805978:web:7b6d50a0dba3fdeaee0963',
    messagingSenderId: '185980805978',
    projectId: 'rtrx-cc137',
    authDomain: 'rtrx-cc137.firebaseapp.com',
    storageBucket: 'rtrx-cc137.firebasestorage.app',
    measurementId: 'G-WLVZLXQD9Y',
  );
}
